log:
  path: /tmp/daily_problem.log
gin:
  port: 5001
  mode: debug
mysql:
  host: chaosi-zju.com:3306
  username: root
  password: ssbb
  database: daily_problem
cron:
  update_problem: '0 0 0 * * *'
problem:
  default_daily_num: 3