log:
  path: /tmp/daily_problem.log
gin:
  port: 5001
  mode: release
mysql:
  host: ${MYSQL_HOST}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWD}
  database: daily_problem
cron:
  pick_problem: '30 0 0 * * ?'
problem:
  default_daily_num: 3

