log:
  path: /tmp/daily_problem.log
gin:
  port: 5001
  mode: debug
mysql:
  host: 127.0.0.1:3306
  username: root
  password: ssbb
  database: daily_problem
cron:
  pick_problem: '0 0 0 * * *'
problem:
  default_daily_num: 3