name: Build And Deploy
on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@master
        with:
            go-version: 1.14

      - name: Set up Node
        uses: actions/setup-node@master

      - name: Check out code
        uses: actions/checkout@master

      - name: Build
        run: |
          make build_server
          make build_client

      - name: Scp to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "output/*"
          target: "~/release/daily-problem"
          rm: true
          strip_components: 1
          command_timeout: 15m

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cp -rfa ~/release/daily-problem/server ~/chaosi/server/daily-problem
            cp -rfa ~/release/daily-problem/dist ~/chaosi/node/daily-problem
            systemctl disable daily_problem.service
            systemctl stop daily_problem.service
            cp -rf ~/release/daily-problem/server/daily_problem.service /etc/systemd/system/
            systemctl enable daily_problem.service
            systemctl start daily_problem.service
            systemctl status daily_problem.service



