name: Build And Deploy
on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@master
        with:
            go-version: 1.14

      - name: Set up Node
        uses: actions/setup-node@master

      - name: Check out code
        uses: actions/checkout@master

      - name: Build
        run: |
          make build_server
          make build_client
          tar -zcvf release.tgz output

      - name: Scp to deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "release.tgz"
          target: "~/chaosi"
