name: Release And Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.12

      - name: Set up Node
        uses: actions/setup-node@master

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          make build_server
          make build_client